### PR TITLE
Use runtime 47

### PR DESCRIPTION
**Pull request by yakushabb**
GNOME runtime version 45 has already reached EOL.

### CODE REVIEW

**Comment by yakushabb** [comment]
@bbhtt ready for review.

**Comment by bbhtt** [comment]
the icon from about the window seems gone Was that present before this PR?

**Comment by yakushabb** [comment]
> the icon from about window seems gone Was that present before this PR?

Nope

image

**Comment by yakushabb** [comment]
And fixed.

image

**Pull request merged**
